### ISSUE TITLE
How to trigger by code

### ISSUE THREAD

**Issue by TimKieu** [candidosales/svelte-google-translate#4]
I have an i18n language menu to change UI element language.
But using Google translate in Blog pages only, it changes all the site pages.

how can I change Google translate to language by code? Similar to i18n lang-switch menu.

Thanks much.

**Comment by candidosales** [comment]
It's a great question; my first assumption is to change the value of the cookie `googtrans`.

Example of how to set cookies with Svelte: https://svelte.dev/tutorial/kit/cookies

Evidence below:

https://github.com/user-attachments/assets/9cd25a3b-9e7a-4fb2-aef0-3022fa7e7abc

I hope this can help you!

**Comment by TimKieu** [comment]
Great option! Thanks much @candidosales 
I am trying to use your great component to replace svelte-i18n for both UI/UX element and blog content.
Merry Christmas and Happy New Year! @candidosales
